# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
        ('wishlist', '0002_remove_product_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(to='login_register.User'),
        ),
    ]
